### ISSUE TITLE
how do I use this?

### ISSUE THREAD

**Issue by foobarbecue** [coin3d/ivexamples#5]
Looks like a nice setup you have here, but with all the cfg stuff and install script and bootstrap stuff I can't tell what is supposed to run what to build what. How do I make it go?

**Comment by foobarbecue** [comment]
Oh, looks like I just run `cmake .` and then `make`?

**Comment by VolkerEnderlein** [comment]
First make sure you have a working Coin3D setup either by building Coin on your machine, or by downloading the build artifacts from the releases. Make sure you include the GUI toolkit binding of your choice (SoWin, SoQt, SoWx, SoXt) when building. 

Then the typical configure/build commands in parent dir of the cloned `ivexamples` dir (make sure to include the submodules when cloning) would read for SoQt, Visual Studio 2019, 64 bit, and Qt 6.5.2:

```
cmake -S ivexamples -B ivexamples_build -G "Visual Studio 16 2019" -A x64 -DGui=Qt -DCMAKE_PREFIX_PATH=C:\Coin3D;C:\Qt\6.5.2\msvc2019_64
cmake --build ivexamples_build --target ALL_BUILD --config Release

```

**Comment by foobarbecue** [comment]
Thanks! I guess it might make sense to add this info to the README?

**Comment by VolkerEnderlein** [comment]
Done. See the updated README.
